export const PROJECT_CATEGORIES = [
  "WEB_DEVELOPMENT",
  "MOBILE_DEVELOPMENT",
  "UI_UX_DESIGN",
  "GRAPHIC_DESIGN",
  "CONTENT_WRITING",
  "DIGITAL_MARKETING",
  "DATA_SCIENCE",
  "AI_ML",
  "DEVOPS",
  "CYBER_SECURITY",
  "OTHER",
];

export const PROJECT_TYPES = [
  "FIXED_PRICE",
  "HOURLY",
];

export const EXPERIENCE_LEVELS = [
  "BEGINNER",
  "INTERMEDIATE",
  "EXPERT",
];