spring.application.name=orivex-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/orivex}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Muskan@2021#}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080



# Show SQL in logs
logging.level.org.hibernate.SQL=DEBUG

# Show parameter values
logging.level.org.hibernate.orm.jdbc.bind=TRACE

jwt.secret=MyVeryLongSecretKeyForDevelopmentOnlyChangeInProduction123456789
jwt.expiration=86400000

file.upload-dir=uploads

razorpay.key-id=rzp_test_TCxmx9yBmHDcwn
razorpay.key-secret=UZ8DcbeqJ1Pk1t7fpx8UmgNB

livekit.api.key=API6SftDZc7tkpN
livekit.api.secret=WE0u6Jf6AFEhSiO9ftMZoM9w1GPfIsFIP4fJX7tMsg6B
livekit.url=wss://orivex-1bqx5a1e.livekit.cloud