server.port=${PORT:8080}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

file.upload-dir=${FILE_UPLOAD_DIR:uploads}

razorpay.key-id=${RAZORPAY_KEY_ID}
razorpay.key-secret=${RAZORPAY_KEY_SECRET}

livekit.api.key=${LIVEKIT_API_KEY}
livekit.api.secret=${LIVEKIT_API_SECRET}
livekit.url=${LIVEKIT_URL}